name: Build and Test with Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - name: Show settings
      run:  echo '${{toJSON(vars)}}'

  clang:
    strategy:
      fail-fast: false

      matrix:
        platform:   [macos-latest, ubuntu-latest, windows-latest]
        qt_version: [6.2.4, 6.5.3, 6.6.1, msys2]
        compiler:   [clang++-14, clang++-15, clang++-16, clang++-17]

        include:
        - platform:         macos-latest
          compiler:         clang++-15
          compiler_command: clang++
          homebrew_path:    $(brew --prefix llvm@15)/bin

        - platform:         windows-latest
          compiler:         clang++-16
          compiler_command: clang++

        - platform:         windows-latest
          compiler:         clang++-17
          compiler_command: clang++
          msys2_system:     clang64
          msys2_arch:       clang-x86_64
          qt_version:       msys2

        exclude:
        - qt_version: msys2               # Available for Windows only, skip for all others

        - platform: macos-latest          # The pre-installed Clang is just slightly too old to support
          compiler: clang++-14            # proper C++ 20. Let's revisit later, now it's too much work.
        - platform: macos-latest          # Not pre-installed on this runner
          compiler: clang++-16
        - platform: macos-latest          # Not pre-installed on this runner
          compiler: clang++-17

        - platform: ubuntu-latest         # Cannot parse its own <chrono> header
          compiler: clang++-14
        - platform: ubuntu-latest         # Not pre-installed on this runner
          compiler: clang++-16
        - platform: ubuntu-latest         # Not pre-installed on this runner
          compiler: clang++-17

        - platform: windows-latest        # Not pre-installed on this runner
          compiler: clang++-14
        - platform: windows-latest        # Not pre-installed on this runner
          compiler: clang++-15
        - platform: windows-latest        # Qt 6.2.4 passes MSVC switches to Clang
          compiler: clang++-16
          qt_version: 6.2.4
        - platform: windows-latest        # Test with MSYS2 version of Qt only
          compiler: clang++-17

    needs: status
    uses: ./.github/workflows/autotest.yml
    if:   ${{ vars.CLANG_ENABLED != '0' }}
    with:
      compiler:       ${{matrix.compiler_command || matrix.compiler}}
      homebrew_path:  ${{matrix.homebrew_path}}
      msys2_arch:     ${{matrix.msys2_arch}}
      msys2_system:   ${{matrix.msys2_system}}
      platform:       ${{matrix.platform}}
      qt_version:     ${{matrix.qt_version}}
