name: Build and Test with MSVC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - name: Show settings
      run:  echo '${{toJSON(vars)}}'

  msvc:
    strategy:
      fail-fast: false

      matrix:
        platform:   [windows-latest]
        qt_version: [6.2.4, 6.5.3, 6.6.1]
        compiler:   [cl]

    needs: status
    uses: ./.github/workflows/autotest.yml
    if:   ${{ vars.MSVC_ENABLED != '0' }}
    with:
      compiler:        ${{ matrix.compiler_command || matrix.compiler }}
      homebrew_path:   ${{ matrix.homebrew_path }}
      msys2_system:    ${{ matrix.msys2_system }}
      platform:        ${{ matrix.platform }}
      qt_version:      ${{ matrix.qt_version }}
      reporting:       ${{ matrix.qt_version == '6.6.1' }}


  reporting:
    needs: msvc
    uses: ./.github/workflows/reporting.yml
    with:
      reporting_tool: reporting-tool-Qt-6.6.1-Windows-cl
      platform:       windows-latest
      qt_tools:       tools_ninja
      qt_version:     6.6.1
