name: Build and Test with GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - name: Show settings
      run:  echo '${{ toJSON(vars) }}'

  gcc:
    strategy:
      fail-fast: false

      matrix:
        platform:   [macos-latest, ubuntu-latest, windows-latest]
        qt_version: [6.2.4, 6.5.3, 6.6.1, msys2]
        msys2:      ['', 'mingw', 'ucrt']
        compiler:   [g++, g++-12]

        include:
        - platform:   windows-latest
          msys2:      mingw
          qt_version: msys2
          compiler:   g++
        - platform:   windows-latest
          msys2:      ucrt
          qt_version: msys2
          compiler:   g++

        exclude:
        - platform:   macos-latest
          qt_version: msys2
        - platform:   macos-latest
          msys2:      mingw
        - platform:   macos-latest
          msys2:      ucrt
        - platform:   macos-latest
          compiler:   g++

        - platform:   ubuntu-latest
          qt_version: msys2
        - platform:   ubuntu-latest
          msys2:      mingw
        - platform:   ubuntu-latest
          msys2:      ucrt
        - platform:   ubuntu-latest
          compiler:   g++-12

        - platform:   windows-latest

    needs: status
    uses: ./.github/workflows/autotest.yml
    if:   ${{ vars.GCC_ENABLED != '0' }}
    with:
      compiler:       ${{matrix.compiler}}
      homebrew_path:  ${{matrix.homebrew_path}}
      msys2_arch:     ${{(matrix.msys2 == 'mingw' && 'x86_64')
                       ||(matrix.msys2 && format('{0}-x86_64', matrix.msys2))
                       || ''}}
      msys2_system:   ${{matrix.msys2 && format('{0}64',      matrix.msys2) || ''}}
      platform:       ${{matrix.platform}}
      qt_version:     ${{matrix.qt_version}}
